# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


pool:
  name: Default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    #jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    


- task: Docker@2
  inputs:
    containerRegistry: 'acr'
    command: 'login'

- task: CmdLine@2
  inputs:
    script: |
            cd $(Build.SourcesDirectory)
            sudo docker build . -t hellospring123.azurecr.io/hello-spring:latest
            #sudo docker run -d -p 8080:9080 -t hellospring123.azurecr.io/hello-spring:latest 
            sudo docker push hellospring123.azurecr.io/hello-spring:latest

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'aks-test'
    manifests: '**/hello-spring.yaml'