---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hworld-dep
 labels:
  app: hworld
spec:
 replicas: 2
 selector:
  matchLabels:
   app: hworld
 template:
  metadata:
   labels:
    app: hworld
  spec:
   containers:
   - name: hworld
     image: docker.io/afrin123/hello-spring:latest
     ports:
     - containerPort: 9080
